[package]
name = "hello-ngx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
bench = false
path = "src/hello_ngx.rs"
crate-type = ["cdylib"]

[dependencies]
ngx = "0.3.0-beta"

[features]
linux = []
